### ISSUE TITLE
no lib, make error. 

### ISSUE THREAD

**Issue by violetrose16** [socram8888/amiitool#12]
[root@****~]# cd amiitool
[root@*** amiitool]# make
"make" lib -C /root/amiitool/mbedtls CFLAGS="-DMBEDTLS_CONFIG_FILE='\"/root/amiitool/configs/mbedtls.h\"' -Wall -pedantic -O2 -fsigned-char"
make[1]: Entering directory '/root/amiitool/mbedtls'
make[1]: *** No rule to make target 'lib'.  Stop.
make[1]: Leaving directory '/root/amiitool/mbedtls'
make: *** [Makefile:57: mbedtls] Error 2

I looked for install lib on arch linux on google.com but not find it. 
Where i can install lib and other on arch linux?

**Comment by socram8888** [comment]
Did you also check out the mbedtls submodule?

**Comment by violetrose16** [comment]
I found other issue, git submodule update --init --recursive
make and make install.
