### ISSUE TITLE
Where to get the keys?

### ISSUE THREAD

**Issue by GalaxyGamingBoy** [socram8888/amiitool#14]
I have an o3ds with wuiimbo. I don't have the nfc reader/writer cause all of them are out of stock. I save the bins from my amiibo cards and when I enter them, it says they are encrypted and to use this tool to decrypt. But I can't find they keys for the -k command argument.

**Comment by socram8888** [comment]
I was going to share them here since I guess no one cares anymore, but it seems I lost them at some point. You'd have to look for them on your favorite search engine.
